import express from 'express';
import http from 'http';
import cors from 'cors';
import pg from 'pg';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import {Server as SocketServer} from 'socket.io';
import path from 'path';
import {fileURLToPath} from 'url';
import fs from 'fs';
const {Pool}=pg; const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); const server=http.createServer(app); const io=new SocketServer(server,{cors:{origin:true,credentials:true}});
const PORT=process.env.PORT||3000; const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
app.use(cors()); app.use(express.json({limit:'4mb'})); app.use(express.static(path.join(__dirname,'public')));
const q=(text,params=[])=>pool.query(text,params); const secret=()=>process.env.JWT_SECRET||'dev-secret-change-me';
const sign=u=>jwt.sign({id:u.id,role:u.role,storeId:u.store_id||null,name:u.name},secret(),{expiresIn:'7d'});
const auth=(roles=[])=>(req,res,next)=>{try{const t=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(t,secret());if(roles.length&&!roles.includes(req.user.role))return res.status(403).json({error:'无权限'});next()}catch(e){res.status(401).json({error:'登录已失效'})}};
async function log(req,action,entity,entityId,detail={}){await q('INSERT INTO audit_logs(user_id,action,entity,entity_id,detail) VALUES($1,$2,$3,$4,$5)',[req.user?.id||null,action,entity,String(entityId??''),JSON.stringify(detail)])}
function changed(){io.emit('data:changed',{at:new Date().toISOString()})}
async function seed(){const st=await q('SELECT count(*) FROM stores');if(+st.rows[0].count===0){const r=await q("INSERT INTO stores(name,address,login_code,manager_name) VALUES('咸阳店','咸阳市','BAKE2024','李店长') RETURNING id");await q("INSERT INTO users(name,store_id,role) VALUES('李店长',$1,'store')",[r.rows[0].id]);await q("INSERT INTO users(name,role,password_hash) VALUES('运营','ops',$1),('管理员','admin',$2)",[await bcrypt.hash('oneira2026',10),await bcrypt.hash('oneira2026',10)]);}const f=await q('SELECT count(*) FROM report_fields');if(+f.rows[0].count===0)await q("INSERT INTO report_fields(label,key,field_type,unit,required,sort_order) VALUES ('营业额','revenue','number','元',true,1),('客单量','orders','number','单',true,2),('损耗率','wasteRate','number','%',true,3),('会员新增','members','number','人',false,4)")}
app.get('/api/health',async(_,res)=>{try{await q('SELECT 1');res.json({ok:true,version:'5.0.0'})}catch(e){res.status(503).json({ok:false})}});
app.post('/api/auth/store-login',async(req,res)=>{const {storeName,name,code}=req.body;const r=await q("SELECT u.*,s.name store_name FROM users u JOIN stores s ON s.id=u.store_id WHERE s.name=$1 AND u.name=$2 AND s.login_code=$3 AND u.role='store' AND s.status='active'",[storeName,name,code]);if(!r.rowCount)return res.status(401).json({error:'门店、姓名或口令错误'});res.json({token:sign(r.rows[0]),user:{id:r.rows[0].id,name:r.rows[0].name,role:'store',storeId:r.rows[0].store_id,storeName:r.rows[0].store_name}})});
app.post('/api/auth/staff-login',async(req,res)=>{const {name,password,role}=req.body;const r=await q('SELECT * FROM users WHERE name=$1 AND role=$2',[name,role]);if(!r.rowCount||!(await bcrypt.compare(password,r.rows[0].password_hash||'')))return res.status(401).json({error:'账号或密码错误'});res.json({token:sign(r.rows[0]),user:{id:r.rows[0].id,name:r.rows[0].name,role:r.rows[0].role}})});
app.get('/api/me',auth(),async(req,res)=>res.json({user:req.user}));
app.get('/api/stores',auth(['ops','admin']),async(_,res)=>res.json((await q('SELECT id,name,address,manager_name,status,created_at FROM stores ORDER BY id')).rows));
app.post('/api/stores',auth(['admin']),async(req,res)=>{const {name,address='',managerName='',code}=req.body;if(!name||!code)return res.status(400).json({error:'门店名称和口令必填'});const r=await q('INSERT INTO stores(name,address,manager_name,login_code) VALUES($1,$2,$3,$4) RETURNING *',[name,address,managerName,code]);if(managerName)await q("INSERT INTO users(name,store_id,role) VALUES($1,$2,'store')",[managerName,r.rows[0].id]);await log(req,'create','stores',r.rows[0].id,{name});changed();res.json(r.rows[0])});
app.patch('/api/stores/:id',auth(['admin']),async(req,res)=>{const {name,address,managerName,code,status}=req.body;const r=await q('UPDATE stores SET name=COALESCE($1,name),address=COALESCE($2,address),manager_name=COALESCE($3,manager_name),login_code=COALESCE($4,login_code),status=COALESCE($5,status) WHERE id=$6 RETURNING *',[name,address,managerName,code,status,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'门店不存在'});if(managerName)await q("UPDATE users SET name=$1 WHERE store_id=$2 AND role='store'",[managerName,req.params.id]);await log(req,'update','stores',req.params.id,{changed:req.body});changed();res.json(r.rows[0])});
app.delete('/api/stores/:id',auth(['admin']),async(req,res)=>{if(req.body.confirm!=='DELETE')return res.status(400).json({error:'需要二次确认'});await q("UPDATE stores SET status='archived' WHERE id=$1",[req.params.id]);await log(req,'archive','stores',req.params.id,{});changed();res.json({ok:true})});
app.get('/api/users',auth(['admin']),async(req,res)=>res.json((await q("SELECT u.id,u.name,u.store_id,u.role,s.name store_name,u.created_at FROM users u LEFT JOIN stores s ON s.id=u.store_id WHERE u.role='store' ORDER BY s.id,u.id")).rows));
app.post('/api/users',auth(['admin']),async(req,res)=>{const {name,storeId}=req.body;if(!name||!storeId)return res.status(400).json({error:'姓名和门店必填'});const r=await q("INSERT INTO users(name,store_id,role) VALUES($1,$2,'store') RETURNING id,name,store_id,role",[name,storeId]);await log(req,'create','users',r.rows[0].id,{name,storeId});changed();res.json(r.rows[0])});
app.delete('/api/users/:id',auth(['admin']),async(req,res)=>{if(req.body.confirm!=='DELETE')return res.status(400).json({error:'需要二次确认'});await q("DELETE FROM users WHERE id=$1 AND role='store'",[req.params.id]);await log(req,'delete','users',req.params.id,{});changed();res.json({ok:true})});
app.get('/api/report-fields',auth(),async(_,res)=>res.json((await q('SELECT * FROM report_fields WHERE enabled=true ORDER BY sort_order,id')).rows));
app.put('/api/report-fields',auth(['admin']),async(req,res)=>{const {fields=[]}=req.body;const keys=new Set();for(const f of fields){if(!f.label||!f.key||keys.has(f.key))return res.status(400).json({error:'日报字段名称或唯一键重复'});keys.add(f.key)}await q('UPDATE report_fields SET enabled=false');for(let i=0;i<fields.length;i++){const f=fields[i];await q(`INSERT INTO report_fields(label,key,field_type,unit,required,sort_order,enabled) VALUES($1,$2,$3,$4,$5,$6,true) ON CONFLICT(key) DO UPDATE SET label=EXCLUDED.label,field_type=EXCLUDED.field_type,unit=EXCLUDED.unit,required=EXCLUDED.required,sort_order=EXCLUDED.sort_order,enabled=true`,[f.label,f.key,f.field_type||'number',f.unit||'',!!f.required,i+1])}await log(req,'update','report_fields','all',{count:fields.length});changed();res.json({ok:true})});
app.get('/api/reports',auth(),async(req,res)=>{let where='',p=[];if(req.user.role==='store'){where='WHERE r.store_id=$1';p=[req.user.storeId]}else if(req.query.storeId){where='WHERE r.store_id=$1';p=[req.query.storeId]}if(req.query.month){where+=(where?' AND ':' WHERE ')+'to_char(r.report_date,\'YYYY-MM\')=$'+(p.length+1);p.push(req.query.month)}res.json((await q(`SELECT r.*,s.name store_name,u.name submitter_name FROM daily_reports r JOIN stores s ON s.id=r.store_id LEFT JOIN users u ON u.id=r.submitted_by ${where} ORDER BY r.report_date DESC,r.id DESC LIMIT 500`,p)).rows)});
app.post('/api/reports',auth(['store','admin']),async(req,res)=>{const storeId=req.user.role==='store'?req.user.storeId:Number(req.body.storeId);const {date,payload={}}=req.body;if(!storeId||!date)return res.status(400).json({error:'缺少门店或日期'});const old=await q('SELECT id,version FROM daily_reports WHERE store_id=$1 AND report_date=$2',[storeId,date]);const r=await q(`INSERT INTO daily_reports(store_id,report_date,submitted_by,payload,version) VALUES($1,$2,$3,$4,1) ON CONFLICT(store_id,report_date) DO UPDATE SET payload=EXCLUDED.payload,submitted_by=EXCLUDED.submitted_by,updated_at=now(),version=daily_reports.version+1 RETURNING *`,[storeId,date,req.user.id,JSON.stringify(payload)]);await q(`UPDATE tasks t SET actual_value=COALESCE((r.payload->>'revenue')::numeric,0),status=CASE WHEN COALESCE((r.payload->>'revenue')::numeric,0)>=t.target_value THEN 'done' ELSE 'pending' END FROM daily_reports r WHERE t.store_id=$1 AND t.task_date=$2 AND r.store_id=t.store_id AND r.report_date=t.task_date`,[storeId,date]);await log(req,old.rowCount?'update':'create','daily_reports',r.rows[0].id,{date,version:r.rows[0].version});changed();res.json(r.rows[0])});
app.get('/api/goals',auth(),async(req,res)=>{let store=req.user.role==='store'?req.user.storeId:req.query.storeId;let month=req.query.month||new Date().toISOString().slice(0,7);let w='WHERE g.month=$1',p=[month];if(store){w+=' AND g.store_id=$2';p.push(store)}res.json((await q(`SELECT g.*,s.name store_name FROM monthly_goals g JOIN stores s ON s.id=g.store_id ${w} ORDER BY g.id`,p)).rows)});
app.post('/api/goals',auth(['ops','admin']),async(req,res)=>{const {storeId,month,goalValue,rule='average',title='营业额目标',customTargets}=req.body;if(!storeId||!month||Number(goalValue)<=0)return res.status(400).json({error:'门店、月份、目标值必填'});const [y,m]=month.split('-').map(Number),days=new Date(y,m,0).getDate();let targets=[];if(rule==='custom'){if(!Array.isArray(customTargets)||customTargets.length!==days)return res.status(400).json({error:`自定义目标必须提供${days}天数据`});targets=customTargets.map(Number);if(targets.some(x=>!Number.isFinite(x)||x<0)||Math.abs(targets.reduce((a,b)=>a+b,0)-Number(goalValue))>0.01)return res.status(400).json({error:'每日目标之和必须等于月目标'})}else{const weights=Array.from({length:days},(_,i)=>{const dow=new Date(y,m-1,i+1).getDay();return rule==='weekendWeight'&&(dow===0||dow===6)?1.5:1});const sum=weights.reduce((a,b)=>a+b,0);targets=weights.map(w=>Number(goalValue)*w/sum)}const goal=await q(`INSERT INTO monthly_goals(store_id,month,goal_type,goal_value,rule,created_by) VALUES($1,$2,'revenue',$3,$4,$5) ON CONFLICT(store_id,month,goal_type) DO UPDATE SET goal_value=EXCLUDED.goal_value,rule=EXCLUDED.rule,created_by=EXCLUDED.created_by RETURNING *`,[storeId,month,goalValue,rule,req.user.id]);for(let d=1;d<=days;d++){const dt=`${month}-${String(d).padStart(2,'0')}`;await q(`INSERT INTO tasks(store_id,goal_id,title,target_value,unit,task_date) VALUES($1,$2,$3,$4,'元',$5) ON CONFLICT(store_id,goal_id,task_date) DO UPDATE SET target_value=EXCLUDED.target_value,title=EXCLUDED.title`,[storeId,goal.rows[0].id,title,targets[d-1],dt])}await log(req,'upsert','monthly_goals',goal.rows[0].id,{month,goalValue,rule});changed();res.json(goal.rows[0])});
app.get('/api/tasks',auth(),async(req,res)=>{let store=req.user.role==='store'?req.user.storeId:req.query.storeId;let month=req.query.month||new Date().toISOString().slice(0,7);let w='WHERE to_char(t.task_date,\'YYYY-MM\')=$1',p=[month];if(store){w+=' AND t.store_id=$2';p.push(store)}res.json((await q(`SELECT t.*,s.name store_name FROM tasks t JOIN stores s ON s.id=t.store_id ${w} ORDER BY t.task_date`,p)).rows)});
app.patch('/api/tasks/:id',auth(['ops','admin']),async(req,res)=>{const {targetValue,title}=req.body;if(targetValue!==undefined&&Number(targetValue)<0)return res.status(400).json({error:'目标不能为负数'});const r=await q('UPDATE tasks SET target_value=COALESCE($1,target_value),title=COALESCE($2,title) WHERE id=$3 RETURNING *',[targetValue===undefined?null:Number(targetValue),title||null,req.params.id]);await log(req,'update','tasks',req.params.id,req.body);changed();res.json(r.rows[0])});
app.get('/api/issues',auth(),async(req,res)=>{let w=req.user.role==='store'?'WHERE i.store_id=$1':'';let p=req.user.role==='store'?[req.user.storeId]:[];res.json((await q(`SELECT i.*,s.name store_name FROM issues i LEFT JOIN stores s ON s.id=i.store_id ${w} ORDER BY i.created_at DESC LIMIT 300`,p)).rows)});
app.post('/api/issues',auth(['store']),async(req,res)=>{const {type='问题',content=''}=req.body;if(!content.trim())return res.status(400).json({error:'请输入内容'});const r=await q('INSERT INTO issues(store_id,submitter_name,type,content) VALUES($1,$2,$3,$4) RETURNING *',[req.user.storeId,req.user.name,type,content]);await log(req,'create','issues',r.rows[0].id,{});changed();res.json(r.rows[0])});
app.patch('/api/issues/:id',auth(['ops','admin']),async(req,res)=>{const r=await q("UPDATE issues SET status='resolved',handler_id=$1,handled_at=now(),handling_note=$2 WHERE id=$3 RETURNING *",[req.user.id,req.body.note||'',req.params.id]);await log(req,'resolve','issues',req.params.id,{note:req.body.note||''});changed();res.json(r.rows[0])});
app.get('/api/audit',auth(['admin']),async(_,res)=>res.json((await q('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 300')).rows));
app.get('/api/export/reports.csv',async(req,res)=>{try{const t=req.query.token||'';req.user=jwt.verify(t,secret());if(!['ops','admin'].includes(req.user.role))return res.status(403).json({error:'无权限'})}catch(e){return res.status(401).json({error:'登录已失效'})}const month=req.query.month||new Date().toISOString().slice(0,7);const rows=(await q("SELECT r.report_date,s.name store_name,r.payload,u.name submitter_name FROM daily_reports r JOIN stores s ON s.id=r.store_id LEFT JOIN users u ON u.id=r.submitted_by WHERE to_char(r.report_date,'YYYY-MM')=$1 ORDER BY r.report_date,s.id",[month])).rows;const lines=['日期,门店,营业额,客单量,损耗率,会员新增,提交人'];for(const r of rows){const p=r.payload||{};lines.push([r.report_date,r.store_name,p.revenue||'',p.orders||'',p.wasteRate||'',p.members||'',r.submitter_name||''].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(','))}res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="oneira-reports-${month}.csv"`);res.send('\ufeff'+lines.join('\n'))});

app.get('/healthz',(_,res)=>res.status(200).json({ok:true,service:'oneira-v5'}));
io.on('connection',s=>s.emit('ready',{ok:true}));app.get('/*splat',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
async function boot(){const schema=fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8');for(const stmt of schema.split(';').map(x=>x.trim()).filter(Boolean))await q(stmt);await seed();server.listen(PORT,()=>console.log('ONEIRA V5 running on '+PORT))}boot().catch(e=>{console.error(e);process.exit(1)});
